project_name: text_pipeline_1781071569553_5000
dataset:
  configs:
  - type: local
    path: /data/data-juicer_dataset/RedPajama/indices/c4_5000.jsonl
    format: jsonl
export_path: /home/yyw/pipeline_full/results/text/text_pipeline_1781071569553_5000.jsonl
np: 50
use_cache: false
open_tracer: true
process:
- fix_unicode_mapper:
    normalization: NFKD
- whitespace_normalization_mapper: null
- punctuation_normalization_mapper: null
- sentence_split_mapper:
    lang: en
- clean_links_mapper: null
- remove_table_text_mapper: null
- stopwords_filter:
    lang: en
    tokenization: false
    min_ratio: 0.3
    use_words_aug: false
- words_num_filter:
    lang: en
    tokenization: false
    min_num: 161
    max_num: 488
    batch_size: 3
- perplexity_filter:
    lang: en
    max_ppl: 2631
    batch_size: 2
- text_chunk_mapper:
    max_len: 1916
    split_pattern: \n\n
- token_num_filter:
    hf_tokenizer: EleutherAI/pythia-14m
    min_num: 294
    max_num: 1388
- text_action_filter:
    lang: en
- text_entity_dependency_filter:
    lang: en
    any_or_all: any
- language_id_score_filter:
    lang: en
    min_score: 0.8
- word_repetition_filter:
    lang: en
    tokenization: false
    rep_len: 3
    min_ratio: 0.1
    max_ratio: 0.5
    batch_size: 3
- document_simhash_deduplicator:
    tokenization: character
    lowercase: true
    ignore_pattern: \p{P}
op_list_to_trace:
- fix_unicode_mapper
- whitespace_normalization_mapper
- punctuation_normalization_mapper
- sentence_split_mapper
- clean_links_mapper
- remove_table_text_mapper
- stopwords_filter
- words_num_filter
- perplexity_filter
- token_num_filter
- text_action_filter
- text_entity_dependency_filter
- language_id_score_filter
- word_repetition_filter
- document_simhash_deduplicator
