project_name: text_pipeline_1781071569574_2000
dataset:
  configs:
  - type: local
    path: /data/data-juicer_dataset/RedPajama/indices/c4_2000.jsonl
    format: jsonl
export_path: /home/yyw/pipeline_full/results/text/text_pipeline_1781071569574_2000.jsonl
np: 40
use_cache: false
open_tracer: true
process:
- whitespace_normalization_mapper: null
- clean_ip_mapper: null
- clean_copyright_mapper: null
- remove_words_with_incorrect_substrings_mapper:
    lang: en
    tokenization: true
    substrings:
    - <
    - '>'
    - '='
    - '&'
    - '?'
- replace_content_mapper:
    pattern: ●■
    repl: <hide>
- remove_specific_chars_mapper: null
- special_characters_filter:
    min_ratio: 0.0
    max_ratio: 0.2
    batch_size: 3
- text_action_filter:
    lang: en
- words_num_filter:
    lang: en
    tokenization: false
    min_num: 165
    max_num: 632
    batch_size: 2
- maximum_line_length_filter:
    min_len: 317
    max_len: 569
    batch_size: 3
- document_simhash_deduplicator:
    tokenization: character
    lowercase: false
    ignore_pattern: \p{P}
op_list_to_trace:
- whitespace_normalization_mapper
- clean_ip_mapper
- clean_copyright_mapper
- remove_words_with_incorrect_substrings_mapper
- replace_content_mapper
- remove_specific_chars_mapper
- special_characters_filter
- text_action_filter
- words_num_filter
- maximum_line_length_filter
- document_simhash_deduplicator
