project_name: text_pipeline_1781071569336_8000
dataset:
  configs:
  - type: local
    path: /data/data-juicer_dataset/RedPajama/indices/c4_8000.jsonl
    format: jsonl
export_path: /home/yyw/pipeline_full/results/text/text_pipeline_1781071569336_8000.jsonl
np: 40
use_cache: false
open_tracer: true
process:
- fix_unicode_mapper:
    normalization: NFD
- sentence_split_mapper:
    lang: en
- remove_specific_chars_mapper: null
- remove_long_words_mapper:
    min_len: 5
    max_len: 17
- clean_links_mapper: null
- clean_ip_mapper: null
- clean_copyright_mapper: null
- remove_words_with_incorrect_substrings_mapper:
    lang: en
    tokenization: false
    substrings:
    - http
    - www
    - .com
    - href
    - //
- text_action_filter:
    lang: en
- text_entity_dependency_filter:
    lang: en
    any_or_all: any
- language_id_score_filter:
    lang:
    - en
    - zh
    min_score: 0.7
- words_num_filter:
    lang: en
    tokenization: true
    min_num: 142
    max_num: 878
    batch_size: 3
- text_length_filter:
    min_len: 385
    max_len: 1784
- perplexity_filter:
    lang: en
    max_ppl: 852
    batch_size: 3
- word_repetition_filter:
    lang: en
    tokenization: true
    rep_len: 3
    min_ratio: 0.1
    max_ratio: 0.15
    batch_size: 2
- document_simhash_deduplicator:
    tokenization: space
    lowercase: false
    ignore_pattern: \p{P}
op_list_to_trace:
- fix_unicode_mapper
- sentence_split_mapper
- remove_specific_chars_mapper
- remove_long_words_mapper
- clean_links_mapper
- clean_ip_mapper
- clean_copyright_mapper
- remove_words_with_incorrect_substrings_mapper
- text_action_filter
- text_entity_dependency_filter
- language_id_score_filter
- words_num_filter
- text_length_filter
- perplexity_filter
- word_repetition_filter
- document_simhash_deduplicator
