project_name: text_pipeline_1781071569397_5000
dataset:
  configs:
  - type: local
    path: /data/data-juicer_dataset/RedPajama/indices/c4_5000.jsonl
    format: jsonl
export_path: /home/yyw/pipeline_full/results/text/text_pipeline_1781071569397_5000.jsonl
np: 50
use_cache: false
open_tracer: true
process:
- whitespace_normalization_mapper: null
- punctuation_normalization_mapper: null
- fix_unicode_mapper:
    normalization: NFC
- remove_table_text_mapper: null
- clean_ip_mapper: null
- replace_content_mapper:
    pattern: \d+(?:,\d+)*
    repl: <hide>
- remove_repeat_sentences_mapper:
    lowercase: true
- remove_words_with_incorrect_substrings_mapper:
    lang: en
    tokenization: true
    substrings:
    - http
    - www
    - .com
    - href
    - //
- remove_specific_chars_mapper: null
- sentence_split_mapper:
    lang: en
- clean_links_mapper: null
- text_chunk_mapper:
    max_len: 880
    split_pattern: \n
- maximum_line_length_filter:
    min_len: 189
    max_len: 824
    batch_size: 2
- text_entity_dependency_filter:
    lang: en
    any_or_all: all
- word_repetition_filter:
    lang: en
    tokenization: true
    rep_len: 20
    min_ratio: 0.0
    max_ratio: 0.5
    batch_size: 2
- perplexity_filter:
    lang: en
    max_ppl: 2476
    batch_size: 2
- average_line_length_filter:
    min_len: 96
    max_len: 7457
    batch_size: 3
- stopwords_filter:
    lang: en
    tokenization: false
    min_ratio: 0.3
    use_words_aug: false
- document_simhash_deduplicator:
    tokenization: character
    lowercase: false
    ignore_pattern: \p{P}
op_list_to_trace:
- whitespace_normalization_mapper
- punctuation_normalization_mapper
- fix_unicode_mapper
- remove_table_text_mapper
- clean_ip_mapper
- replace_content_mapper
- remove_repeat_sentences_mapper
- remove_words_with_incorrect_substrings_mapper
- remove_specific_chars_mapper
- sentence_split_mapper
- clean_links_mapper
- maximum_line_length_filter
- text_entity_dependency_filter
- word_repetition_filter
- perplexity_filter
- average_line_length_filter
- stopwords_filter
- document_simhash_deduplicator
