project_name: text_pipeline_1781071569387_1000
dataset:
  configs:
  - type: local
    path: /data/data-juicer_dataset/RedPajama/indices/c4_1000.jsonl
    format: jsonl
export_path: /home/yyw/pipeline_full/results/text/text_pipeline_1781071569387_1000.jsonl
np: 50
use_cache: false
open_tracer: true
process:
- whitespace_normalization_mapper: null
- remove_words_with_incorrect_substrings_mapper:
    lang: en
    tokenization: false
    substrings:
    - <
    - '>'
    - '='
    - '&'
    - '?'
- clean_ip_mapper: null
- sentence_split_mapper:
    lang: en
- remove_long_words_mapper:
    min_len: 3
    max_len: 15
- remove_repeat_sentences_mapper:
    lowercase: false
- language_id_score_filter:
    lang: en
    min_score: 0.7
- character_repetition_filter:
    rep_len: 15
    min_ratio: 0.0
    max_ratio: 0.3
    batch_size: 3
- average_line_length_filter:
    min_len: 27
    max_len: 5968
    batch_size: 2
- stopwords_filter:
    lang: en
    tokenization: false
    min_ratio: 0.3
    use_words_aug: true
- document_simhash_deduplicator:
    tokenization: character
    lowercase: false
    ignore_pattern: \p{P}
op_list_to_trace:
- whitespace_normalization_mapper
- remove_words_with_incorrect_substrings_mapper
- clean_ip_mapper
- sentence_split_mapper
- remove_long_words_mapper
- remove_repeat_sentences_mapper
- language_id_score_filter
- character_repetition_filter
- average_line_length_filter
- stopwords_filter
- document_simhash_deduplicator
